# Generated by Django 4.0.4 on 2022-05-02 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Codes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_codes', models.CharField(max_length=20)),
                ('diagnosis_codes', models.CharField(blank=True, max_length=20, null=True)),
                ('full_code', models.CharField(max_length=20)),
                ('abbrev_description', models.TextField(blank=True, null=True)),
                ('full_description', models.TextField(blank=True, null=True)),
                ('category_title', models.TextField(blank=True, null=True)),
                ('version', models.SmallIntegerField(default=10)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
