# Generated by Django 4.0.4 on 2022-04-30 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codes',
            name='abbrev_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='codes',
            name='category_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
