# Generated by Django 4.0.4 on 2022-04-30 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icd', '0002_alter_codes_abbrev_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codes',
            name='category_codes',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='codes',
            name='full_code',
            field=models.CharField(max_length=20),
        ),
    ]
